export var moviesData = [
  {
    id: '1',
    title: 'Pulp Fiction',
    description: 'Action & Advanture',
    about: 'Bohemian Rhapsody is a 2018 biographical drama film about Freddie Mercury, the lead singer of the British rock band Queen. It was directed by Bryan Singer from a screenplay by Anthony McCarten, and produced by Graham King and Queen manager Jim Beach.',
    img_url: 'https://miro.medium.com/max/1200/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg',
    year: '2004',
    rating: '4.3',
    duration: '195',
  },
  {
    id: '2',
    title: 'Bohemian Rhapsody',
    description: 'Drama, Biography, Music',
    about: 'Bohemian Rhapsody is a 2018 biographical drama film about Freddie Mercury, the lead singer of the British rock band Queen. It was directed by Bryan Singer from a screenplay by Anthony McCarten, and produced by Graham King and Queen manager Jim Beach.',
    img_url: 'https://cdn.eso.org/images/thumb300y/eso1907a.jpg',
    year: '2003',
    rating: '4.3',
    duration: '195',
  },
  {
    id: '3',
    title: 'Bill: Vol 2',
    description: 'Oscar winning Movie',
    about: 'Bohemian Rhapsody is a 2018 biographical drama film about Freddie Mercury, the lead singer of the British rock band Queen. It was directed by Bryan Singer from a screenplay by Anthony McCarten, and produced by Graham King and Queen manager Jim Beach.',
    img_url: 'https://docs.microsoft.com/ru-ru/windows/uwp/design/controls-and-patterns/images/image_licorice.jpg',
    year: '1994',
    rating: '4.3',
    duration: '195',
  },
  {
    id: '4',
    title: 'Pulp Fiction',
    description: 'Action & Advanture',
    about: 'Bohemian Rhapsody is a 2018 biographical drama film about Freddie Mercury, the lead singer of the British rock band Queen. It was directed by Bryan Singer from a screenplay by Anthony McCarten, and produced by Graham King and Queen manager Jim Beach.',
    img_url: 'https://lh3.googleusercontent.com/Zl7XwhbI_UOgTd92AEBiWFZLBd-LjIe3lSuIh2hhcRXo2c7yInDiqjioRhNbvxpRdTiU9cAdhw=w640-h400-e365-rj-sc0x00ffffff',
    year: '2004',
    rating: '4.3',
    duration: '195',
  },
  {
    id: '5',
    title: 'Bohemian Rhapsody',
    description: 'Drama, Biography, Music',
    about: 'Bohemian Rhapsody is a 2018 biographical drama film about Freddie Mercury, the lead singer of the British rock band Queen. It was directed by Bryan Singer from a screenplay by Anthony McCarten, and produced by Graham King and Queen manager Jim Beach.',
    img_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-fff2lftqIE077pFAKU1Mhbcj8YFvBbMvpA&usqp=CAU',
    year: '2003',
    rating: '4.3',
    duration: '195',
  },
  {
    id: '6',
    title: 'Bill: Vol 2',
    description: 'Oscar winning Movie',
    about: 'Bohemian Rhapsody is a 2018 biographical drama film about Freddie Mercury, the lead singer of the British rock band Queen. It was directed by Bryan Singer from a screenplay by Anthony McCarten, and produced by Graham King and Queen manager Jim Beach.',
    img_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDkvFCLSMbUU6Bqb1m-0y3LPAQ7_Gcs-PNZw&usqp=CAU',
    year: '1994',
    rating: '4.3',
    duration: '195',
  },
]

